version: "3.3"
services:
  redis:
    image: redis
    restart: unless-stopped
    hostname: redis
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # command:
    #   - server
    # env_file: .env
    environment:
      REDIS_HOST: redis
    ports:
      - 8080:8080
